# Generated by Django 2.0.1 on 2018-03-18 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_courseorg_course_nums'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseorg',
            name='course_nums',
        ),
    ]
