# Generated by Django 2.0.1 on 2018-03-17 17:38

import DjangoUeditor.models
from django.db import migrations, models
import utils.storage


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='生日'),
        ),
        migrations.AlterField(
            model_name='courseorg',
            name='describe',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='机构描述'),
        ),
        migrations.AlterField(
            model_name='courseorg',
            name='image',
            field=models.ImageField(storage=utils.storage.ImageStorage(), upload_to='org/%Y/%m', verbose_name='封面图'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default='', storage=utils.storage.ImageStorage(), upload_to='teacher/%Y/%m', verbose_name='头像'),
        ),
    ]
