# Generated by Django 2.0.1 on 2018-02-27 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20180221_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='category',
            field=models.CharField(choices=[('train', '培训机构'), ('colleges', '高校'), ('personal', '个人')], default='train', max_length=20, verbose_name='机构类别'),
        ),
    ]
