# Generated by Django 2.0.1 on 2018-03-07 15:00

from django.db import migrations, models
import utils.storage


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20180305_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_file',
            field=models.FileField(default='', storage=utils.storage.ImageStorage(), upload_to='videos/%Y/%m', verbose_name='课程视频'),
        ),
    ]
